meta_product_name: "Alvéole"
meta_title: "Alvéole - Le 1er site de mise en relation de maraudes"
meta_description: "Et si vous donniez un peu de votre temps pour changer la vie des plus démunis ?"
# meta_image: "mains.jpg" # should exist in `app/assets/images/`

